import PropertyLawCore

/// Renders a `ConformanceMap` to the `*.generated.swift` text the plugin
/// writes (PRD §5.3 sample output). Output is fully deterministic: same
/// input map → byte-identical string. The idempotence test in
/// `EmitterGoldenTests` enforces this.
///
/// Structure:
///   1. Provenance header (target name, type count, re-run command,
///      parse-failure list when any).
///   2. `import Testing` + `import PropertyLawKit`.
///   3. Per-type `@Suite struct <TypeName>PropertyLawTests` with
///      `@Test func <protocol>_<TypeName>()` methods, one per surviving
///      conformance after PRD §4.3 most-specific dedupe (already applied
///      by `ModuleScanner`).
///
/// Suppression markers (`// property-law-suppress: <protocol>_<TypeName>`)
/// are honored when present in the input set — the corresponding `@Test`
/// is replaced with a comment-only stub that preserves the marker on
/// future regenerations (commit 6).
enum GeneratedFileEmitter {

    /// Stable ordering of `@Test func` methods within each emitted suite.
    /// `KnownProtocol.allCases` order matches the M1 macro's
    /// `stableOrder` so plugin-emitted and macro-emitted output sort
    /// identically when a project mixes both forms.
    private static let testEmissionOrder = KnownProtocol.allCases

    static func emit(
        target: String,
        map: ConformanceMap,
        suppressions: Set<String> = [],
        extraImports: [String] = []
    ) -> String {
        var lines: [String] = []
        lines.append(contentsOf: headerLines(target: target, map: map))
        lines.append("")
        lines.append("import Testing")
        lines.append("import PropertyLawKit")
        // **The module under test, imported `@testable`.** Without this line
        // the file names types it never imported and nothing it emits compiles
        // — the suites went out referencing `Foo` with only `Testing` and
        // `PropertyLawKit` in scope. Measured across swift-collections,
        // swift-numerics and swift-async-algorithms: 180 detected types, none
        // of them nameable.
        //
        // `@testable` rather than a plain import because roughly half those
        // types are `internal` (20 public / 19 not, on the unique names in that
        // corpus), and a plain import would reach only the public half while
        // silently dropping the rest at compile time. `@testable` is also what
        // the strategist's `.separateFile` reachability assumes — it promotes
        // `internal`, which is exactly where that table draws its line.
        //
        // Two shapes this does not rescue, both by construction: `private` and
        // `fileprivate` types, which `@testable` cannot promote (the scanner
        // declines to emit a suite for them — see `ConformanceMap`), and a
        // `--output` path inside the scanned target itself, where the module
        // would be importing itself. The default output path
        // (`Tests/<Target>Tests/`) is a separate target and does not hit that.
        lines.append("@testable import \(target)")
        // Modules that *declare* types this file names. Plain `import`, not
        // `@testable`: a foreign module's `internal` API is out of reach anyway
        // (`skipReason` drops those), and `@testable` across a package boundary
        // needs the dependency built with testability, which is not ours to
        // assume.
        let foreignModules = Set(map.entries.compactMap(\.declaringModule))
            .subtracting([target])
        // Imports required by derived generators (e.g. `Foundation` for a
        // `Date` member), plus any the caller asked for with `--extra-import`
        // — the opt-in path for a module that *supplies* generators, such as
        // `PropertyLawSyntax` answering `Syntax.gen()`. Not inferred, because
        // guessing an import for an opt-in product breaks every project that
        // does not depend on it.
        let generatorImports = map.entries.reduce(into: Set<String>()) {
            $0.formUnion($1.derivationStrategy.requiredImports)
        }
        // Sorted and unioned for deterministic output; empty for a
        // stdlib-only target with no context, so existing files are unchanged.
        for module in foreignModules.union(generatorImports)
            .union(extraImports).subtracting([target]).sorted() {
            lines.append("import \(module)")
        }
        for entry in map.entries {
            lines.append("")
            lines.append(contentsOf: suiteLines(for: entry, suppressions: suppressions))
        }
        return lines.joined(separator: "\n") + "\n"
    }

    // MARK: - Header

    private static func headerLines(target: String, map: ConformanceMap) -> [String] {
        var lines: [String] = []
        lines.append("// GENERATED by PropertyLawDiscoveryPlugin — DO NOT EDIT outside")
        lines.append("// `// property-law-suppress: <protocol>_<TypeName>` markers.")
        lines.append("//")
        lines.append("// Target: \(target)")
        lines.append("// Types detected: \(map.entries.count)")
        lines.append("// Re-run: swift package propertylawcheck discover --target \(target)")
        if !map.parseFailures.isEmpty {
            lines.append("//")
            lines.append("// Parse failures (\(map.parseFailures.count)):")
            for failure in map.parseFailures {
                lines.append("//   - \(failure.filePath): \(failure.message)")
            }
        }
        // Same rationale as the parse-failure block: a type that disappears
        // from a generated file with no note reads as "nothing to test".
        if !map.skippedTypes.isEmpty {
            lines.append("//")
            lines.append("// Detected but skipped — a suite for these would not compile "
                + "(\(map.skippedTypes.count)):")
            for type in map.skippedTypes {
                lines.append("//   - \(type.typeName): \(type.explanation)")
            }
        }
        return lines
    }

    // MARK: - Per-type suite

    private static func suiteLines(
        for entry: ConformanceMap.Entry,
        suppressions: Set<String>
    ) -> [String] {
        var lines: [String] = []
        lines.append(provenanceComment(for: entry))
        // Skip entries whose conformance set is empty after the upstream
        // most-specific + unemittable filter (`ModuleScanner`) — typically
        // types whose only recognized stdlib conformance is `IteratorProtocol`
        // or `Strideable`, neither of which the plugin can emit a compilable
        // call for from inheritance-clause syntax alone.
        guard !entry.conformances.isEmpty else {
            lines.append("// No emit-able stdlib conformance recognized.")
            return lines
        }
        lines.append("@Suite struct \(suiteName(for: entry.typeName)) {")
        let generatorExpr = GeneratorExpressionEmitter.expression(
            typeName: entry.typeName,
            strategy: entry.derivationStrategy
        )
        let orderedConformances = testEmissionOrder.filter { entry.conformances.contains($0) }
        for (index, conformance) in orderedConformances.enumerated() {
            if index > 0 { lines.append("") }
            // Same spelling as the emitted `@Test func`, via the one converter
            // — a marker the user copies out of the file has to match the test
            // it suppresses, and a nested type's qualified name would otherwise
            // give the two different strings.
            let suppressionKey = PropertyLawTestStub.testName(
                conformance: conformance, typeName: entry.typeName
            )
            if suppressions.contains(suppressionKey) {
                lines.append(contentsOf: suppressedTestLines(
                    suppressionKey: suppressionKey,
                    conformance: conformance,
                    typeName: entry.typeName
                ))
            } else {
                lines.append(contentsOf: testLines(
                    conformance: conformance,
                    typeName: entry.typeName,
                    generatorExpr: generatorExpr
                ))
            }
        }
        lines.append("}")
        return lines
    }

    /// `BitSet.Counted` → `BitSet_CountedPropertyLawTests`. The suite name is
    /// an identifier; the type reference inside it stays qualified.
    private static func suiteName(for typeName: String) -> String {
        "\(QualifiedTypeName.identifier(for: typeName))PropertyLawTests"
    }

    private static func provenanceComment(for entry: ConformanceMap.Entry) -> String {
        let summary = entry.provenances
            .map { "\($0.filePath):\($0.line) (\($0.kind.rawValue))" }
            .joined(separator: ", ")
        return "// \(entry.typeName) — \(summary)"
    }

    // MARK: - Test method

    private static func testLines(
        conformance: KnownProtocol,
        typeName: String,
        generatorExpr: String
    ) -> [String] {
        PropertyLawTestStub.lines(
            conformance: conformance,
            typeName: typeName,
            generatorExpr: generatorExpr
        )
    }

    private static func suppressedTestLines(
        suppressionKey: String,
        conformance: KnownProtocol,
        typeName: String
    ) -> [String] {
        // Marker preserved verbatim; the test body is replaced with a
        // comment-only stub so the surrounding suite still compiles and
        // the marker survives the next regeneration.
        return [
            "    // property-law-suppress: \(suppressionKey)",
            "    // (\(conformance.checkFunctionName) for \(typeName) suppressed by user marker)"
        ]
    }
}
