/// Structured representation of a composed generator — the tree the string
/// emitters render. Introduced as Phase 1 of generator scaffolding (see
/// `git show e8f1ac4:docs/GENERATOR_SCAFFOLDING_DESIGN.md` — pruned as superseded):
/// replacing the opaque emitted
/// string with a tree is what later lets a slot be a `.hole` (Phase 2) and
/// lets SwiftInferProperties refine/fill nodes structurally (Phase 4).
///
/// This phase covers only the nodes the composite parser
/// (`composedGenerator`) produces — leaves and collection wrappers. Product
/// (memberwise / init / enum-payload) and sum (`oneOf`) nodes, plus the
/// `.hole` placeholder, arrive with the partial-derivation phases. Output is
/// byte-identical to the previous string emitter (locked by existing tests).
public indirect enum GeneratorPlan: Sendable, Equatable {
    /// A fully-resolved generator expression and the modules it must name —
    /// a recognized raw / known value type, or an inlined / `Type.gen()`
    /// reference produced by the custom-type resolver.
    case leaf(expression: String, imports: Set<String>)
    /// `T?` → `<element>.optional`.
    case optional(GeneratorPlan)
    /// `[T]` → `<element>.array(of: 0...8)`.
    case array(GeneratorPlan)
    /// `Set<T>` → `<element>.set(ofAtMost: 0...8)`.
    case set(GeneratorPlan)
    /// `[K: V]` → `zip(<key>, <value>).dictionary(ofAtMost: 0...8)`.
    case dictionary(key: GeneratorPlan, value: GeneratorPlan)
    /// An unresolvable slot — a type with no derivable generator. Renders as
    /// a Swift editor placeholder for the developer to fill (scaffolding).
    case hole(typeName: String, reason: String)
    /// A **self-referential** type, generated by a depth-budgeted helper
    /// function emitted alongside the expression.
    ///
    /// Recursion is the one shape that cannot be inlined — the resolver's
    /// whole contract is "inline the nested generator so the stub is
    /// self-contained", and an expression cannot contain itself. So this node
    /// renders as a *call* and carries the `func` it calls in
    /// `supportingDeclarations`, which the stub writer emits above the check.
    case recursive(
        typeName: String,
        helperName: String,
        declaration: String,
        imports: Set<String>
    )
    /// The recursion point itself, valid only *inside* a `.recursive`
    /// declaration body. Renders as `helper(budget - 1)` in the recursive
    /// arm and as a terminal (empty / nil) in the base arm — which is why the
    /// wrapper node above it has to be the one that decides, see
    /// `renderedBase`.
    case selfReference(typeName: String, helperName: String)

    /// The `swift-property-based` source expression for this plan. A `.hole`
    /// renders as a `<#Generator<T>#>` editor placeholder.
    public var rendered: String {
        switch self {
        case .leaf(let expression, _):
            return expression
        case .optional(let element):
            return "\(element.rendered).optional"
        case .array(let element):
            return "\(element.rendered).array(of: 0...8)"
        case .set(let element):
            return "\(element.rendered).set(ofAtMost: 0...8)"
        case .dictionary(let key, let value):
            return "zip(\(key.rendered), \(value.rendered)).dictionary(ofAtMost: 0...8)"
        case .hole(let typeName, _):
            return "<#Generator<\(typeName)>#>"
        case .recursive(_, let helperName, _, _):
            return "\(helperName)(\(Self.defaultDepthBudget))"
        case .selfReference(_, let helperName):
            return "\(helperName)(budget - 1)"
        }
    }

    /// Starting depth for a recursive generator.
    ///
    /// Branching types grow exponentially in the budget — a two-child node at
    /// budget 6 is up to 127 nodes — while the laws that need recursion
    /// (idempotence of a rewrite, round-tripping a tree) are refuted by
    /// *shallow* witnesses. The probe behind this feature found its minimal
    /// counterexample at depth 4 and shrank it to depth 4, so 4 is the measured
    /// number rather than a guessed one.
    public static let defaultDepthBudget = 4

    /// The base arm of a `.recursive` helper: the same tree with every
    /// recursion point collapsed to a terminal value.
    ///
    /// This exists because `Gen.array(of:)` **eagerly evaluates** its element
    /// generator. A budget check written inside the expression
    /// (`.array(of: budget > 0 ? 0...8 : 0...0)`) still *constructs*
    /// `helper(budget - 1)` to pass as the element, which constructs
    /// `helper(budget - 2)`, and so on past zero — infinite recursion at
    /// generator-construction time, before a single value is drawn. So the
    /// helper needs a real early return, and that needs a second rendering
    /// where the recursion points are gone.
    ///
    /// The **wrapper decides the terminal**, which is why `.selfReference`
    /// cannot render one on its own: `[Node]` collapses to `[]` and `Node?` to
    /// `nil`, but a *bare* self-reference has no terminal at all — a type whose
    /// member is unconditionally itself is uninhabitable, and `nil` is returned
    /// so the caller falls back to `.todo`.
    public var renderedBase: String? {
        switch self {
        case .leaf(let expression, _):
            return expression
        case .selfReference:
            // No wrapper above us to supply a terminal — uninhabitable.
            return nil
        case .optional(let element):
            if case .selfReference(let typeName, _) = element {
                return "Gen<\(typeName)?>.always(nil)"
            }
            return element.renderedBase.map { "\($0).optional" }
        case .array(let element):
            if case .selfReference(let typeName, _) = element {
                return "Gen<[\(typeName)]>.always([])"
            }
            return element.renderedBase.map { "\($0).array(of: 0...8)" }
        case .set(let element):
            if case .selfReference(let typeName, _) = element {
                return "Gen<Set<\(typeName)>>.always([])"
            }
            return element.renderedBase.map { "\($0).set(ofAtMost: 0...8)" }
        case .dictionary(let key, let value):
            if case .selfReference(let typeName, _) = value {
                return "Gen<[\(key.rendered): \(typeName)]>.always([:])"
            }
            guard let keyBase = key.renderedBase,
                  let valueBase = value.renderedBase else { return nil }
            return "zip(\(keyBase), \(valueBase)).dictionary(ofAtMost: 0...8)"
        case .hole(let typeName, _):
            return "<#Generator<\(typeName)>#>"
        case .recursive(_, let helperName, _, _):
            return "\(helperName)(\(Self.defaultDepthBudget))"
        }
    }

    /// `func` declarations `rendered` calls and the stub must therefore emit
    /// above the check. Empty for every non-recursive plan, so existing
    /// consumers that ignore it are unaffected.
    public var supportingDeclarations: [String] {
        switch self {
        case .leaf, .hole, .selfReference:
            return []
        case .optional(let element), .array(let element), .set(let element):
            return element.supportingDeclarations
        case .dictionary(let key, let value):
            return key.supportingDeclarations + value.supportingDeclarations
        case .recursive(_, _, let declaration, _):
            return [declaration]
        }
    }

    /// Whether this tree contains a recursion point — the test the resolver
    /// uses to decide a plan needs wrapping in a `.recursive` helper.
    public var containsSelfReference: Bool {
        switch self {
        case .selfReference:
            return true
        case .leaf, .hole, .recursive:
            return false
        case .optional(let element), .array(let element), .set(let element):
            return element.containsSelfReference
        case .dictionary(let key, let value):
            return key.containsSelfReference || value.containsSelfReference
        }
    }

    /// Modules `rendered` must be able to name (unioned over the tree).
    public var requiredImports: Set<String> {
        switch self {
        case .leaf(_, let imports):
            return imports
        case .optional(let element), .array(let element), .set(let element):
            return element.requiredImports
        case .dictionary(let key, let value):
            return key.requiredImports.union(value.requiredImports)
        case .hole, .selfReference:
            return []
        case .recursive(_, _, _, let imports):
            return imports
        }
    }

    /// `true` when no slot in the tree is a `.hole` — i.e. fully derivable.
    public var isComplete: Bool {
        switch self {
        case .leaf, .recursive:
            return true
        case .optional(let element), .array(let element), .set(let element):
            return element.isComplete
        case .dictionary(let key, let value):
            return key.isComplete && value.isComplete
        case .hole:
            return false
        // A bare recursion point outside a `.recursive` body is a resolver bug,
        // not a derivable generator.
        case .selfReference:
            return false
        }
    }
}
